package-lock.json, package.json, src/__snapshots__/App.test.js.snap
`"node-sass": "^4.12.0",
"normalize.css": "^8.0.1",
"prop-types": "^15.7.2",
"enzyme-to-json": "^3.3.5"`
`Install dependencies for project setup`
NA
=> Add dependencies for files

.circleci/config.yml, src/components/App/__snapshots__/App.test.js.snap, src/index.js, src/reducers/resourcesReducer/index.js
`NA`
`NA`
`Add the rootreducer file to the store and `
=> created circle.ci file

src/Sass/index.scss, src/components/App/__snapshots__/App.test.js.snap, src/components/App/index.js, src/components/Error/Error.test.js, src/components/Error/__snapshots__/Error.test.js.snap, src/components/Error/index.js, src/components/Nav/Nav.test.js, src/components/Nav/_Nav.scss, src/components/Nav/__snapshots__/Nav.test.js.snap, src/components/Nav/index.js, src/container/TicketDashboard/__snapshots__/TicketDashbord.test.js.snap, src/container/TicketDashboard/index.js
`Add Navigation menu with test and conditional rendering`
`Clicking the hamburger bar will render a menu`
`Do you think the Sass and variables are consistent with our agreed practices?`
=> Setup circl ci

src/actions/actions.test.js, src/actions/index.js, src/reducers/index.js, src/reducers/ticketsReducer/index.js, src/reducers/ticketsReducer/ticketsReducer.test.js, src/thunks/getActiveTickets/getActiveTickets.test.js, src/thunks/getActiveTickets/index.js
- Create setActiveTickets action
- Create ticketsReducer
- Create getActiveTickets thunk
- Test all the above
=> Tickets thunk

src/actions/actions.test.js, src/actions/index.js, src/components/App/__snapshots__/App.test.js.snap, src/components/App/index.js, src/components/Nav/__snapshots__/Nav.test.js.snap, src/components/Nav/index.js, src/components/TicketForm/index.js, src/container/TicketDashboard/index.js, src/reducers/ticketsReducer/index.js, src/reducers/ticketsReducer/ticketsReducer.test.js, src/thunks/postTicket/index.js, src/thunks/postTicket/postTicket.test.js
Created a POST thunk to post a new ticket
Created a addTicket action
Implemented ADD_TICKET case in ticketsReducer
Tested the action, reducer, thunk
Created basic ticket form with: 
- Due Date
- Text Field for ticket notes
- Radio buttons for ticket priority
- Submit Button
**Tested everything except TicketForm**
- [] Yes
=> Ticket form

README.md, src/Utility/MockData.js, src/actions/index.js, src/reducers/index.js, src/reducers/resourcePartsReducer/index.js, src/reducers/resourcePartsReducer/resourcePartsReducer.test.js, src/thunks/getResourceParts/getResourceParts.test.js, src/thunks/getResourceParts/index.js, src/thunks/postTicket/index.js
- Add part thunk
- Add part reducer
- Add test for reducer, thunks, action creators
=> Thunk parts

.env, src/actions/index.js, src/thunks/getActiveTickets/getActiveTickets.test.js, src/thunks/getActiveTickets/index.js, src/thunks/getResourceParts/getResourceParts.test.js, src/thunks/getResourceParts/index.js, src/thunks/postLoginUser/index.js, src/thunks/postPart/index.js, src/thunks/postResource/index.js, src/thunks/postResource/postResource.test.js, src/thunks/postTicket/index.js, src/thunks/postTicket/postTicket.test.js
- Add env file
- Create base url variable
=> Create Env file

.env, src/thunks/postLoginUser/postLoginUser.test.js
- Updated env base url variable to use aws url
=> Update env base url to aws url

src/Sass/index.scss, src/components/Card/_Card.scss, src/components/Card/index.js, src/components/CardContainer/_CardContainer.scss, src/components/CardContainer/index.js
Co-authored-by: Mike <kingstockton@gmail.com>
- Add icons
- Style Card header
=> Style cards

.eslintrc.js, package-lock.json, package.json, src/Utility/MockData.js, src/components/App/__snapshots__/App.test.js.snap, src/components/App/index.js, src/components/Card/Card.test.js, src/components/Card/_Card.scss, src/components/Card/__snapshots__/Card.test.js.snap, src/components/Card/index.js, src/components/CardContainer/CardContainer.test.js, src/components/CardContainer/_CardContainer.scss, src/components/CardContainer/index.js, src/components/Dashboard/Dashbord.test.js, src/components/Dashboard/__snapshots__/Dashbord.test.js.snap, src/components/Dashboard/index.js, src/components/Nav/Nav.test.js, src/components/Nav/_Nav.scss, src/components/Nav/__snapshots__/Nav.test.js.snap, src/components/Nav/index.js, src/components/UserLogin/index.js
``npm i`` for eslint@5.16.0
`Add testing and Card display along with eslint`
=> Form version2

public/index.html, src/Utility/MockData.js, src/components/App/__snapshots__/App.test.js.snap, src/components/App/index.js, src/components/Card/Card.test.js, src/components/Card/_Card.scss, src/components/Card/__snapshots__/Card.test.js.snap, src/components/Card/index.js, src/components/CardContainer/_CardContainer.scss, src/components/CardContainer/index.js, src/components/Dashboard/index.js, src/components/Nav/_Nav.scss, src/thunks/getParts/getResourceParts.test.js, src/thunks/getParts/index.js
`Clicking a resource will now fetch all parts associated with that resource`
=> Fetch partsfrom resource

src/components/App/__snapshots__/App.test.js.snap, src/components/Card/__snapshots__/Card.test.js.snap, src/components/CreateUser/index.js
Check user password length
Check password and confirmation password match
=> Check passwords and make error message

src/components/CardContainer/_CardContainer.scss
`Add style for  CardContainer`
=> Mmedia qv1

src/Sass/index.scss, src/components/CreateItem/_CreateItem.scss, src/components/CreateItem/index.js, src/components/CreateUser/index.js
Style createItem button
Position fixed the button
=> Create item btn

src/components/Nav/_Nav.scss
Give the nav bar and mobile menu fixed positioning so they stay on the page if the user scrolls down.
=> Change mobile-menu to position fixed

src/components/Card/_Card.scss, src/components/Card/__snapshots__/Card.test.js.snap, src/components/Card/index.js, src/components/CardContainer/_CardContainer.scss
`Add card scss for user interaction`
`Just updated some p tags and scss infomation`
=> Update card visual

src/actions/actions.test.js, src/actions/index.js, src/components/Card/__snapshots__/Card.test.js.snap, src/reducers/index.js, src/reducers/pathReducer/index.js
Delete path action and reducer
=> Delete path action and reducer

src/components/App/__snapshots__/App.test.js.snap, src/components/App/index.js, src/components/CardContainer/index.js, src/components/Dashboard/index.js, src/components/DynamicForm/index.js, src/components/Form/index.js
=> Dynamic form

src/Sass/index.scss, src/Utility/Config/FormConfig.js, src/components/App/__snapshots__/App.test.js.snap, src/components/App/index.js, src/components/Card/__snapshots__/Card.test.js.snap, src/components/Card/index.js, src/components/CardContainer/index.js, src/components/CreateUser/_CreateUser.scss, src/components/CreateUser/index.js, src/components/DynamicForm/_DynamicForm.scss, src/components/DynamicForm/index.js, src/components/Form/index.js, src/components/Loading/Loading.js, src/components/Loading/_Loading.scss, src/components/Nav/__snapshots__/Nav.test.js.snap, src/components/Nav/index.js, src/thunks/fetchCollection/index.js, src/thunks/postPart/index.js
=> Form configuration

src/components/App/App.test.js, src/components/App/__snapshots__/App.test.js.snap, src/components/App/index.js
Fix loading bar so it conditionally renders
=> Fix loading

src/components/Nav/_Nav.scss
Change header to black and white
=> Style header

.env, src/Sass/index.scss, src/Utility/Config/FormConfig.js, src/components/Card/__snapshots__/Card.test.js.snap, src/components/TicketForm/_TicketForm.scss, src/components/TicketForm/index.js, src/containers/App/__snapshots__/App.test.js.snap, src/containers/App/index.js
=> Add ticketform component

src/containers/App/App.test.js, src/containers/App/index.js
Redirect user based on if logged in or not.
=> Redirect home

src/components/Card/index.js, src/components/TicketForm/_TicketForm.scss, src/components/TicketForm/index.js, src/containers/CardContainer/index.js, src/thunks/postTicket/index.js
`Add Ticket functionality to create a ticket`
`Added CSS and functionality`
=> Post ticket to backend

src/Utility/Config/FormConfig.js, src/actions/index.js, src/components/Card/__snapshots__/Card.test.js.snap, src/components/TicketForm/_TicketForm.scss, src/components/TicketForm/index.js, src/containers/CreateUser/_CreateUser.scss, src/containers/CreateUser/index.js, src/containers/Nav/_Nav.scss, src/containers/Nav/__snapshots__/Nav.test.js.snap, src/containers/Nav/index.js, src/reducers/resourcePartsReducer/index.js, src/reducers/resourcesReducer/index.js, src/reducers/ticketsReducer/index.js, src/thunks/deleteSession/index.js, src/thunks/postTicket/index.js, src/thunks/postUser/index.js
`Add success message for posting a ticket and log out info in redux`
=> Post resource

src/containers/CardContainer/_CardContainer.scss, src/containers/UserLogin/_UserLogin.scss
-Center header image text
-Add black transparent overlay to make text standout more
-Center header and button on login form
Tested in snapshot
=> Add transparent black overlay to header image and center text

src/components/PartForm/PartForm.test.js, src/components/PartForm/__snapshots__/PartForm.test.js.snap, src/components/PartForm/index.js, src/components/TicketForm/TicketForm.test.js, src/components/TicketForm/__snapshots__/TicketForm.test.js.snap, src/components/TicketForm/index.js
Added snapshots tests for part and tickets forms
=> Form tests

src/containers/CardContainer/index.js, src/thunks/fetchCollection/index.js
Quick fix for fetch collection
=> Fix get tickets

.vscode/settings.json, README.md, src/components/Card/__snapshots__/Card.test.js.snap, src/components/Card/index.js, src/containers/Nav/_Nav.scss
`Fix the sizing issue with the login icon`
=> fix size issue and attach wireframes
